apiVersion: v1
kind: Service
metadata:
  name: workflow1github
  namespace: namespace-workflow-1717689533487
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: workflow1github
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000